theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - toc.follow
    # - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Plugings
plugins:
  - blog:
      blog_toc: true
      post_date_format: long
      post_url_format: "{slug}"
      post_excerpt: required
      post_excerpt_separator: <!-- more -->
      post_readtime: true
      post_readtime_words_per_minute: 265
      archive: true
      archive_name: Archive
      archive_date_format: yyyy
      archive_url_date_format: yyyy
      archive_url_format: "archive/{date}"
      archive_pagination: true
      archive_pagination_per_page: 10
      archive_toc: true
      categories: true
      # categories_name: Categories
      categories_url_format: "category/{slug}"
      categories_pagination: true
      categories_pagination_per_page: 10
      categories_toc: true
      authors: true
      authors_profiles_url_format: "author/{slug}"
      authors_profiles_pagination: true
      authors_profiles_pagination_per_page: 10
      authors_profiles_toc: false
      pagination: true
      pagination_per_page: 10
      pagination_url_format: "page/{page}"
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
      pagination_if_single_page: false
      pagination_keep_content: false
      draft: false
      draft_on_serve: true
      draft_if_future_date: true
  - search

# Extensions
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 3

site_name: Manikanth
site_url: https://manikanthr5.github.io/
site_author: Manikanth Reddy
copyright: Copyright &copy; 2022 @manikanthr5

# Repository
repo_name: manikanthr5/manikanthr5.github.io
repo_url: https://github.com/manikanthr5/manikanthr5.github.io
edit_uri: ""

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/manikanthr5
    - icon: fontawesome/brands/linkedin-in
      link: https://linkedin.com/in/manikanthr5
    - icon: fontawesome/brands/kaggle
      link: https://kaggle/manikanthr5
    - icon: fontawesome/solid/envelope
      link: mailto://manikanth.iitkgp@gmail.com
  analytics:
    provider: google
    property: G-GS41WHEFVR

# Page Tree
nav:
  - Home: index.md
  - Notes:
      - notes/index.md
  - Kaggle:
      - kaggle/index.md
      - Feedback Prize - English Language Learning:
          - kaggle/feedback-prize-english-language-learning/index.md
      - Riiid Answer Correctness Prediction:
          - kaggle/riiid-answer-correctness-prediction/index.md
      - Mechanisms of Action (MoA) Prediction:
          - kaggle/mechanisms-of-action-moa-prediction/index.md
  - Blog:
      - blog/index.md
  - About:
      - About Manikanth Reddy: about/index.md
      - Contact: about/contact.md
      - Disclaimer: about/disclaimer.md
      - List 100: about/list-100.md
      - India Tours: about/india-tours.md
      - Visit 100 Countries: about/visit-100-countries.md
